# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('path', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('access', models.TextField()),
            ],
        ),
    ]
