addons:
  apt:
    packages:
    - libav-tools
after_success: coveralls --merge coconuts/static/coverage/coveralls.json
cache:
  directories:
    - coconuts/static/node_modules
  pip: true
dist: trusty
install:
  - pip install python-coveralls tox
  - cd coconuts/static
  - npm install
  - cd ../..
language: python
script:
  - tox
  - cd coconuts/static
  - npm test -- --single-run
  - cd ../..
